runtime: python39 # Runtime paling stabil untuk static files
service: tcc-sarah

handlers:
  - url: /
    static_files: frontend/pages/index.html
    upload: frontend/pages/index.html

  - url: /(.*)
    static_files: frontend/\1
    upload: frontend/(.*)

# Opsional: biar hemat
automatic_scaling:
  min_instances: 0
  max_instances: 1