FROM node:18
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
# Pastikan port sesuai dengan yang diminta Cloud Run (biasanya 8080)
EXPOSE 8080
CMD [ "node", "--env-file=.env", "app.js" ]
CMD [ "node", "app.js" ]